[GLOBAL]
pants_version = "2.14.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
]

[source]
root_patterns = [
  '/python',
]

[anonymous-telemetry]
enabled = false

[python-bootstrap]
search_path = ["/Users/lingxili/miniforge3/bin"]